name: Fetch Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la
